# frozen_string_literal: true

source "https://rubygems.org"

gem "middleman", "~> 4.4", ">= 4.4.0"
gem "oga", "~> 2.14"
gem "nokogiri", "~> 1.13.9"
gem "middleman-s3_sync"
gem "redcarpet"
gem "rack", ">= 3.0.0"
